site_name: bddjango
site_url: https://www.baidu.com/

nav:
    - Home: index.md
    - QuickStart: QuickStart.md
    - API文档格式说明: FormatDescription.md
    - 关于: about.md
    - ________ad1: ________ad1.md
    - ________ad2: ________ad2.md
    #- ________ad3: advertisement.md


theme: readthedocs

extra_css: [extra.css]




