site_name: bddjango
site_url: https://www.baidu.com/

nav:
    - Home: index.md
    - QuickStart: QuickStart.md
    - API文档格式说明: FormatDescription.md
    - 关于: about.md
    - __点击看广告: advertisement.md

theme: readthedocs

extra_css: [extra.css]




