site_name: bddjango
site_url: https://www.baidu.com/

nav:
    - Home: index.md
    - QuickStart: QuickStart.md
    - API文档格式说明: FormatDescription.md
    - 关于: about.md


#theme: readthedocs
theme: material


extra_css: [extra.css]

extra_javascript: [extra.js, comment.js]
#extra_javascript: [comment.js]

plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'





