site_name: bddjango
site_url: https://www.baidu.com/

nav:
    - Home: index.md
    - QuickStart: QuickStart.md
    - ApiFormatDescription: FormatDescription.md
    - About: about.md
#    - Test: 测试文档.md

theme: readthedocs

extra_css: [extra.css]




